apiVersion: v1
kind: ConfigMap
metadata:
  name: soketi-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "debug": {{ .Values.soketi.config.debug }},
      "port": 6001,
      "appManager": {
        "driver": "array",
        "cache": { "enabled": false, "ttl": -1 },
        "array": {
          "apps": [
            {{- range .Values.soketi.config.apps }}
            {
              "id": "{{ .id }}",
              "key": "{{ .key }}",
              "secret": "{{ .secret }}",
              "maxConnections": -1,
              "enableClientMessages": false,
              "enabled": {{ .enabled | default true }},
              "maxBackendEventsPerSecond": -1,
              "maxClientEventsPerSecond": -1,
              "maxReadRequestsPerSecond": -1,
              "webhooks": []
            }{{ if not (eq (index $.Values.soketi.config.apps (sub (len $.Values.soketi.config.apps) 1)).id .id) }},{{ end }}
            {{- end }}
          ]
        }
      }
    }
