apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.host }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: 3306
      nodePort: {{ .Values.mysql.nodePort }}
  selector:
    app: {{ .Chart.Name }}
    tier: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.host }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
              subPath: mysql-data
            - name: mysql-initdb-config
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /opt/motf/soketi/data
            type: DirectoryOrCreate
        - name: mysql-initdb-config
          configMap:
            name: mysql-initdb-config